version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - grpc-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  grpc-network:
    driver: bridge